# Generated by Django 5.1.3 on 2024-11-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["-created_at"]},
        ),
    ]
