# Generated by Django 5.1.3 on 2024-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_link_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="click",
            name="device_type",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="click",
            name="hour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="click",
            name="weekday",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="click",
            name="country",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="click",
            name="user_agent",
            field=models.TextField(),
        ),
    ]
