# Generated by Django 5.1.3 on 2024-11-27 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_link_short_id_alter_link_user_customdomain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LinkVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("placeholder", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="customdomain",
            name="user",
        ),
        migrations.RemoveField(
            model_name="link",
            name="custom_domain",
        ),
        migrations.AddField(
            model_name="click",
            name="visitor_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(
                fields=["link", "visitor_id"], name="tracker_cli_link_id_a9aa80_idx"
            ),
        ),
        migrations.AddField(
            model_name="clickvariable",
            name="click",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="tracker.click",
            ),
        ),
        migrations.AddField(
            model_name="linkvariable",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="tracker.link",
            ),
        ),
        migrations.AddField(
            model_name="clickvariable",
            name="variable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tracker.linkvariable"
            ),
        ),
        migrations.DeleteModel(
            name="CustomDomain",
        ),
        migrations.AddIndex(
            model_name="clickvariable",
            index=models.Index(
                fields=["variable", "value"], name="tracker_cli_variabl_d124ca_idx"
            ),
        ),
    ]
