# Generated by Django 5.1.3 on 2025-01-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_link_total_clicks_alter_linkvariable_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="linkvariable",
            name="placeholder",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="click",
            name="ip_info",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracker.ipinfo",
            ),
        ),
    ]
